version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: G7H4sH2lamG9a7eh1orst7p2a  # Your root password here
      MYSQL_DATABASE: data_base  # The initial database name
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
